import streamlit as st
import cv2
import numpy as np
import pandas as pd
from tensorflow.keras.models import load_model

import os
import gdown

MODEL_PATH = "blood_group_model.h5"

if not os.path.exists(MODEL_PATH):
    file_id = "1WK3-NsMi4ye9gWqSpLnc8ztcYMxSBmBT"
    url = f"https://drive.google.com/uc?id={file_id}"
    gdown.download(url, MODEL_PATH, quiet=False)

model = load_model(MODEL_PATH)

classes = ['A', 'AB', 'B', 'O']

st.title("Fingerprint Blood Group Detection")

st.sidebar.title("Navigation")

st.sidebar.info("""
Fingerprint Based Blood Group Detection

Mini Project
Using CNN Deep Learning
""")

uploaded_file = st.file_uploader(
    "Upload Fingerprint Image",
    type=["png", "jpg", "jpeg","bmp"]
)

if uploaded_file is not None:

    file_bytes = np.asarray(
        bytearray(uploaded_file.read()),
        dtype=np.uint8
    )

    img = cv2.imdecode(
        file_bytes,
        cv2.IMREAD_GRAYSCALE
    )

    img = cv2.resize(img, (128,128))

    img = img / 255.0

    img = img.reshape(1,128,128,1)

    prediction = model.predict(img)

    predicted_class = np.argmax(prediction)

    confidence = np.max(prediction) * 100

    st.image(
        uploaded_file,
        caption="Uploaded Fingerprint"
    )

    st.success(
        f"Predicted Blood Group: {classes[predicted_class]}"
    )

    st.info(
        f"Confidence Score: {confidence:.2f}%"
    )

    report = f"""
    Fingerprint Blood Group Detection Report

    Predicted Blood Group: {classes[predicted_class]}

    Confidence Score: {confidence:.2f}%

    Generated By:
    Fingerprint Blood Group Detection System
    """

    st.download_button(
        label="Download Prediction Report",
        data=report,
        file_name="blood_group_report.txt",
        mime="text/plain"
    )

    blood_info = {
    "A": "Group A blood contains A antigens.",
    "AB": "Group AB is universal recipient.",
    "B": "Group B blood contains B antigens.",
    "O": "Group O is universal donor."
    }

    st.subheader("Blood Group Information")

    st.subheader("Prediction Summary")

    st.table({
    "Parameter": [
        "Predicted Group",
        "Confidence"
    ],
    "Value": [
        classes[predicted_class],
        f"{confidence:.2f}%"
    ]
    })

    st.subheader("Prediction Summary")

    st.table({
    "Parameter": [
        "Predicted Group",
        "Confidence"
    ],
    "Value": [
        classes[predicted_class],
        f"{confidence:.2f}%"
    ]
    })

    st.subheader("Prediction Probability Analysis")

    prob_df = pd.DataFrame({
    "Blood Group": classes,
    "Probability (%)": prediction[0] * 100
    })

    st.bar_chart(
    prob_df.set_index("Blood Group")
    )

    st.write(
    blood_info[classes[predicted_class]]
    )

    st.write("---")

    st.subheader("Dataset Statistics")

    st.write("""
    Total Images Used: 6000

    A Group : 1500

    AB Group : 1500

    B Group : 1500

    O Group : 1500
    """)

    st.write("---")

    st.subheader("Model Information")

    st.write("""
    Model Type: Convolutional Neural Network (CNN)

    Input Image Size: 128 x 128 pixels

    Training Images: 6000

    Training Epochs: 5

    Output Classes: A, AB, B, O

    Framework: TensorFlow & Keras
    """)

    st.subheader("Project Information")

    st.write("""
    Dataset Used: Fingerprint Blood Group Dataset

    Algorithm: Convolutional Neural Network (CNN)

    Classes:
    - A
    - AB
    - B
    - O
    """)

    st.write("---")

    st.caption(
    "Developed by Ravali,Anusha,Yeshashwi | Fingerprint Blood Group Detection System"
    )